spring:
  application:
    name: c2c-social-govern-reward
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/c2c_social_govern?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall
      initialSize: 1
      maxActive: 50
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 1
      poolPreparedStatements: 'true '
      testOnBorrow: 'false  '
      testOnReturn: 'false  '
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 FROM DUAL
dubbo:
  protocol:
    name: dubbo
    port: 20880
  cloud:
    subscribed-services: c2c-social-govern-reward
  scan:
    base-packages: com.vanguard.c2c.social.govern.reward
